package examen;

import clases.pregunta;
import clases.*;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Preguntas extends javax.swing.JFrame {
    
    public Preguntas() {
        initComponents();
        String[] a = r.setRespuestas(posicion);
        buttonGroup1.clearSelection();
        Materia.setText(p.getPregunta(x,6));
        Contador.setText(p.getPregunta(x,y));
        question.setText(p.getPregunta(x,1));
        opc1.setText(p.getPregunta(x, 2));
        opc2.setText(p.getPregunta(x, 3));
        opc3.setText(p.getPregunta(x, 4));
        String respuesta = p.getPregunta(x,5);
        opc1.requestFocus(false);
        regresar.setEnabled(false);
        termina.setEnabled(false);
        Juego.setEnabled(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
 
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });

    }

    private void close(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
           System.exit(0);
    }
    int x = 0;
    int y = 0;
    
    Object[] select = {"","","","","","","","","","","","","","",""};
    
    int posicion = 0;
    respuestas r = new respuestas();
    pregunta p = new pregunta();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Materia = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        Contador = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        termina = new javax.swing.JButton();
        avanzar = new javax.swing.JButton();
        opc1 = new javax.swing.JRadioButton();
        opc2 = new javax.swing.JRadioButton();
        opc3 = new javax.swing.JRadioButton();
        Juego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PREGUNTAS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        Materia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Materia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Materia.setText("MATERIA:");
        Materia.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Materia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MateriaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Materia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                MateriaComponentHidden(evt);
            }
        });

        question.setBackground(new java.awt.Color(255, 255, 255));
        question.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        question.setText("¿Pregunta 1?");
        question.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        question.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                questionAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Contador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contador.setText("PREGUNTA=1/10");
        Contador.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Contador.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ContadorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        regresar.setText("<<ANTERIOR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        termina.setText("TERMINAR");
        termina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminaActionPerformed(evt);
            }
        });

        avanzar.setText("SIGUIENTE>>");
        avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarActionPerformed(evt);
            }
        });

        buttonGroup1.add(opc1);
        opc1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opc2);
        opc2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opc3);
        opc3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc3ActionPerformed(evt);
            }
        });

        Juego.setText("Juego");
        Juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opc2)
                            .addComponent(opc1)
                            .addComponent(opc3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                                .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(regresar)
                                .addGap(82, 82, 82)
                                .addComponent(termina)
                                .addGap(119, 119, 119)
                                .addComponent(Juego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(avanzar)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Materia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contador, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opc1)
                .addGap(18, 18, 18)
                .addComponent(opc2)
                .addGap(14, 14, 14)
                .addComponent(opc3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresar)
                    .addComponent(termina)
                    .addComponent(avanzar)
                    .addComponent(Juego))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(715, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        if(x == 0){
            regresar.setEnabled(false);
        }
        
        if(x > 0){
            x--;
            avanzar.setEnabled(true);
            Juego.setEnabled(false);
            Materia.setText(p.getPregunta(x,6));
            String[] a = r.setRespuestas(posicion);
           // String respuesta = p.getPregunta(x,5);
            Contador.setText(p.getPregunta(x,y));
            buttonGroup1.clearSelection(); // sirve para borrar las selecciones de los radio button
            opc1.setText(p.getPregunta(x, 2));
            opc2.setText(p.getPregunta(x, 3));
            opc3.setText(p.getPregunta(x, 4));
            opc1.requestFocus();
        }else{
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_regresarActionPerformed

    private void terminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminaActionPerformed
        double respuesta_correctas = 0;
        int incorrectas = y;
        Juego.setEnabled(true);
        
        for(int i = 0; i < 15; i++){
            
            if(select[i].equals(r.getRespuesta(i))){
                respuesta_correctas = respuesta_correctas + 1.5;
                Juego.setEnabled(true);
            }else{
                incorrectas = incorrectas + 1;
            }
            if(respuesta_correctas>=7){
                Juego.setEnabled(true);
            }else{
            }
        }
        
        respuesta_correctas = respuesta_correctas /2;
        
          JOptionPane.showMessageDialog(null, "Tu calificacion es " +  respuesta_correctas);
          JOptionPane.showMessageDialog(null, "Tu Respuestas Incorrectas Fueron " + incorrectas);
    }//GEN-LAST:event_terminaActionPerformed

    private void avanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarActionPerformed
        // TODO add your handling code here:
       if(x == 14){
            avanzar.setEnabled(false);
            termina.setEnabled(true);
        }
       
        if(x < 14){
            regresar.setEnabled(true);
            x++;
            Juego.setEnabled(false);
            Materia.setText(p.getPregunta(x,6));
            //String respuesta = p.getPregunta(x,5);
            String[] a = r.setRespuestas(posicion);
            question.setText(p.getPregunta(x,1));
            Contador.setText(p.getPregunta(x, y));
            buttonGroup1.clearSelection(); // sirve para borrar las selecciones de los radio button
            opc1.setText(p.getPregunta(x,2));
            opc2.setText(p.getPregunta(x,3));
            opc3.setText(p.getPregunta(x,4));
            opc1.requestFocus();
        }else{
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_avanzarActionPerformed

    private void questionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_questionAncestorAdded
     
    }//GEN-LAST:event_questionAncestorAdded

    private void MateriaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MateriaAncestorAdded
        
    }//GEN-LAST:event_MateriaAncestorAdded

    private void ContadorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ContadorAncestorAdded
     
    }//GEN-LAST:event_ContadorAncestorAdded

    private void MateriaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MateriaComponentHidden

    }//GEN-LAST:event_MateriaComponentHidden

    private void opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc1ActionPerformed
     select [x] = opc1.getLabel();
    }//GEN-LAST:event_opc1ActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed
     select [x] = opc2.getLabel();
    }//GEN-LAST:event_opc2ActionPerformed

    private void opc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc3ActionPerformed
     select [x] = opc3.getLabel();
    }//GEN-LAST:event_opc3ActionPerformed

    private void JuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegoActionPerformed
       new inicio().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contador;
    private javax.swing.JButton Juego;
    private javax.swing.JLabel Materia;
    private javax.swing.JButton avanzar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opc1;
    private javax.swing.JRadioButton opc2;
    private javax.swing.JRadioButton opc3;
    private javax.swing.JLabel question;
    private javax.swing.JButton regresar;
    private javax.swing.JButton termina;
    // End of variables declaration//GEN-END:variables

    private static class select {

        public select() {
        }
    }
}
